### ISSUE TITLE
Consider some optimizations on git-annex objects and special remote objects layout

### ISSUE THREAD

**Issue by yarikoptic** [datalad/git-annex-ria-remote#18]
Per https://git-annex.branchable.com/tuning/ you could probably benefit from at least `annex.tune.branchhash1=true` for your special remote, but might be worth also using `annex.tune.objecthash1=true` for the datasets themselves.

**Comment by mih** [comment]
The issue with that is the viral property of this approach. From the linked page:

> Also, it's not safe to merge two separate git repositories that have been tuned differently (or one tuned and the other one not). git-annex will prevent merging their git-annex branches together, but it cannot prevent git merge remote/master merging two branches, and the result will be ugly at best (git annex fix can fix up the mess somewhat).

As we don't have a comprehensive idea (yet) on how targeted scenarios will be affected, we decided to keep things standard for now.

**Comment by yarikoptic** [comment]
Sure, it's up to you. So far though we didn't see any merges like that. I am thinking even that we should have used them for all datalad datasets by default.... But now might be too late

**Comment by bpoldrack** [comment]
> I am thinking even that we should have used them for all datalad datasets by default.

To - by default - be incompatible with standard annex remotes? Naahh.

**Comment by yarikoptic** [comment]
> To - by default - be incompatible with standard annex remotes? Naahh.

I am not sure what those "standard annex remotes" are.  Those are initiated per dataset, so if dataset initiates/configures it with that new setting -- everything will be as good as before, just with lighter impact on inodes.  It is only in the case of the same special remote reused across different datasets (Which is a "no no" on its own) - that is where you would get into some kind of problem.
or am I missing something?

**Comment by bpoldrack** [comment]
> It is only in the case of the same special remote reused across different datasets

Why special remotes? You can have a simple git-annex repository as a remote (across several datasets). Right now, that's fine. With a tuned annex as default, it's not. You then can only interact with remotes using the same tunings or am I wrong? There are annexes out there (like collections of conference proceedings, videos, what ever) that I could use with a dataset I created (including merges). With such a tuned default I would become incompatible with those, making it more difficult to interact with the plain-annex-world. Why would I want to limit ourselves or at least make that a more difficult task? I don't see a benefit that's worth separating the world of plain annex repositories from datalad datasets in terms of collaboration and integration.
In my view those should be fully compatible by default. It shouldn't take a particular reason to fit in with them rather than the other way around.

**Comment by yarikoptic** [comment]
> There are annexes out there (like collections of conference proceedings, videos, what ever) that I could use with a dataset I created (including merges).

have you ever merged some other, independently initiated repository/dataset, into another one ?  ATM it is not even allowed by git to merge independent histories without an additional switch.

so once again -- yes, hypothetically it could trouble but so far I think I had no such use case in all of my use of thousands of repositories/annexes.

**Comment by mih** [comment]
Revisiting this issue. I think I am missing how tuning could be performed per remote. AFAICS tuning is a property of a dataset, because the content that is commited requires compatibility of all clones. Hence, whoever creates a dataset determines its nature forever:

```
mih@meiner /tmp/tuning % git init
Initialized empty Git repository in /tmp/tuning/.git/
mih@meiner /tmp/tuning (git)-[master] % git -c annex.tune.objecthash1=true annex init
init  (scanning for unlocked files...)
ok
(recording state in git...)
mih@meiner /tmp/tuning (git)-[master] % echo 123 . > this
mih@meiner /tmp/tuning (git)-[master] % git annex add this
add this 
ok                                
(recording state in git...)
mih@meiner /tmp/tuning (git)-[master] % git commit -m 'this'
[master (root-commit) 7312a4b] this
 1 file changed, 1 insertion(+)
 create mode 120000 this
mih@meiner /tmp/tuning (git)-[master] % git cat-file -p master:this
.git/annex/objects/KM/SHA256E-s6--6f0f6e15b5d24d0be88032f41497822b9726f14e12efa035c17479a3d4ab4c02/SHA256E-s6--6f0f6e15b5d24d0be88032f41497822b9726f14e12efa035c17479a3d4ab4c02%          mih@meiner /tmp/tuning (git)-[master] % cd ..
mih@meiner /tmp % git clone tuning tclone
Cloning into 'tclone'...
done.
mih@meiner /tmp % cd tclone
mih@meiner /tmp/tclone (git)-[master] % git annex init
init  (merging origin/git-annex into git-annex...)

git-annex: Remote repository is tuned in incompatible way; cannot be merged with local repository.
failed
git-annex: init: 1 failed
```

Sure thing, code could be written to change what is in the branches, but that would only make the clone incompatible with any existing clones.

So when you are saying

> So far though we didn't see any merges like that.

What do you mean by that? I cannot think of a any merge across clones that would NOT be affected.

**Comment by yarikoptic** [comment]
```
mih@meiner /tmp/tclone (git)-[master] % git annex init
init  (merging origin/git-annex into git-annex...)
```
;-) indeed all merges will be like this, but I meant merges of initialized annex repos. Here I think it is deficiency of annex in not checking remote git-annex branch first for options, or may be even not starting from it and then just adding a new uuid. Worth bringing up with @joeyh

**Comment by mih** [comment]
> I meant merges of initialized annex repos

But it would need to be "identically initialized annex repos", which implies that the dataset creator determines the nature of any clone forever. Hence, there is nothing we can do per remote.

**Comment by yarikoptic** [comment]
yes, but I don't see a problem with that.

**Comment by mih** [comment]
Me neither, but we can close this issue in that case ;-)
